export enum ErrorCode {
  VALIDATION = 'VALIDATION',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  DOMAIN_RULE = 'DOMAIN_RULE',
  UPSTREAM = 'UPSTREAM',
  INTERNAL = 'INTERNAL',
}
